### ISSUE TITLE
LongBeard Design Tweaks

### ISSUE THREAD

**Issue by rbayly** [xpologistics/Griffon#106]
Suzanne is looking at out longbeard app

**Comment by gkilmain** [comment]
@rbayly @suzanneXPO I have made changes to classnames in [GIT-94](https://github.com/xpologistics/Griffon/tree/GIT-94-GeorgeKilmain-Enhancements-to-LongBeard) so we need to make sure she has latest. Do you want me to pull request what I have? I've tested everything locally and its working.

**Comment by gkilmain** [comment]
@suzanneXPO As we talked about please style an `.active` class for the nav.
