### ISSUE TITLE
The JS is just is a bunch of functions in a file with no real structure

### ISSUE THREAD

**Issue by gkilmain** [xpologistics/Griffon#131]
**Thinking long term** Wanted to get thoughts about making the preview app more manageable since already the file has grown from a few lines to about 100. If we do want to do this (I'm in favor of it) do we want to use a transpiler like Babel, should it be written in typescript, should we use a tried and true approach like revealing module, etc. Just wanted to start a conversation around this. @rbayly @zenjay240

**Comment by rbayly** [comment]
This is pretty much a static app, so don't want to get to crazy with it, once its built we really won't touch it except to add areas to the sand-box, so this can be kept the way it is for now, we might revisit this later,
