### ISSUE TITLE
MD Library Not Working in LongBeard

### ISSUE THREAD

**Issue by rbayly** [xpologistics/Griffon#77]
The MD Library is not working in the Longbeard system, need to find out why and fix it.

**Comment by AncelHernandez** [comment]
https://github.com/xpologistics/Griffon/blob/master/src/longbeard/system-config.ts the material path was incorrect. instead of ``` '@angular/material':'vendor/@angular/material/material.umd.js',
 ```  it should be ``` '@angular/material':'vendor/@angular/material/bundles/material.umd.js', ```

**Comment by rbayly** [comment]
Completed and Set for Next Release

**Comment by rbayly** [comment]
When using the MD Elements in the Preview Application it is throwing an error

zone.js:388 Unhandled Promise rejection: Template parse errors:
'md-button' is not a known element:

If 'md-button' is an Angular component, then verify that it is part of this module.
If 'md-button' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("




[ERROR ->]




"): elementsView@45:16 ; Zone: ; Task: Promise.then ; Value: Error: Template parse errors:
'md-button' is not a known element:
If 'md-button' is an Angular component, then verify that it is part of this module.
If 'md-button' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("




[ERROR ->]




"): elementsView@45:16
at TemplateParser.parse

**Comment by AncelHernandez** [comment]
cause of error was because material updated how they call md-button. its now a directive instead of its own component 
Wrong: `<md-button> click me </md-button>` 
Right: `<button md-button> click me </button>`
