### ISSUE TITLE
Flesh out Support Page

### ISSUE THREAD

**Issue by rbayly** [xpologistics/Griffon#86]
Flesh out the longbeard support page and how to get support.

**Comment by rbayly** [comment]
The Support Page (Link off of the cog icon in the upper right hand side of Longbeard, needs something to contact the group for support of the product, not sure if we should have a message system or a simple email form, I will leave it up to you , but the basic requirements are they need to be able to contact us if they run into trouble.

**Comment by AncelHernandez** [comment]
Updated the support page to include a slack icon with a link that opens up slack and redirects them to the `#angular` page. Also included a link to my email followed by a mail icon that when clicked it opens up outlook and with the `to:` field populated with my email and the `subject:` to be `Griffon Support`

# Code snippits:
Slack redirect:
```
<a href="slack://channel?team=T0C265BHN&id=C2T1TM6G5"><div md-card-avatar class="slack-logo"></div></a>

```
Email
```
<a href="support">ancel.hernandez@xpo.com</a><a href="mailto:ancel.hernandez@xpo.com?subject=Griffon Support"><md-icon>mail</md-icon></a>

```
