### ISSUE TITLE
Enhancements to LongBeard

### ISSUE THREAD

**Issue by rbayly** [xpologistics/Griffon#94]
General Enhancements to LongBeard Application

**Comment by gkilmain** [comment]
@rbayly Some things i noticed. 

- Prevent vertical scrollbar on window from showing if window is smaller than requested iframe width. Scroll bar should only be visible inside iframe
- Give a percent width option in addition to pixels. 
- Refactor css / js into their own files. 
- Add an `active` indication to active menu item
- Make input box focused on page load. 
- Add vertical scroll bar so users can click and drag ( I think this should be its own ticket as its a bit more involved. Maybe a feature for 1.X )
